"""New column color in Kategorie

Revision ID: 29b99bc787a9
Revises: bdedc0e8a55c
Create Date: 2025-11-12 12:22:28.639232

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29b99bc787a9'
down_revision = 'bdedc0e8a55c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('kategorie', schema=None) as batch_op:
        batch_op.add_column(sa.Column('color_hex', sa.String(length=7), nullable=False, server_default='#94a3b8'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('kategorie', schema=None) as batch_op:
        batch_op.drop_column('color_hex')

    # ### end Alembic commands ###
