"""First migration

Revision ID: bdedc0e8a55c
Revises: 
Create Date: 2025-11-12 08:39:11.280284

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bdedc0e8a55c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kategorie',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nazev', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nazev')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    op.create_table('polozka_zasoby',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nazev', sa.String(length=150), nullable=False),
    sa.Column('mnozstvi_v_baleni', sa.Float(), nullable=True),
    sa.Column('minimum_pro_upozorneni', sa.Float(), nullable=True),
    sa.Column('popis_baleni', sa.String(length=200), nullable=True),
    sa.Column('kategorie_id', sa.Integer(), nullable=False),
    sa.Column('uzivatel_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['kategorie_id'], ['kategorie.id'], ),
    sa.ForeignKeyConstraint(['uzivatel_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('polozka_zasoby')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))

    op.drop_table('user')
    op.drop_table('kategorie')
    # ### end Alembic commands ###
